#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: remove-ncs2 <node name>"
    exit 1
fi

curl --header "Content-Type: application/json-patch+json" \
--request PATCH \
--data '[{"op": "remove", "path": "/status/capacity/thkukuk.de~1NCS2"}]' \
http://localhost:8001/api/v1/nodes/$1/status
